
  CREATE TABLE "DBAMV"."PW_REGISTRO_ALTA" 
   (	"CD_REGISTRO_ALTA" NUMBER(8,0) NOT NULL ENABLE, 
	"DT_REGISTRO_ALTA" DATE, 
	"CD_ATENDIMENTO" NUMBER, 
	"CD_PRESTADOR" NUMBER(12,0), 
	"CD_DOCUMENTO_CLINICO" NUMBER(8,0), 
	"CD_USUARIO" VARCHAR2(30 BYTE), 
	"TP_SITUACAO" VARCHAR2(20 BYTE), 
	"DS_OBS_ALTA" VARCHAR2(2000 BYTE), 
	"CD_ATENDIMENTO_PAI" NUMBER(10,0), 
	"CD_MOT_ALT" NUMBER, 
	"DT_ALTA_MEDICA" DATE, 
	"HR_ALTA_MEDICA" DATE, 
	"DT_PREVISTA_ALTA" DATE, 
	"CD_SETOR_OBITO" NUMBER(4,0), 
	"NR_DECLARACAO_OBITO" VARCHAR2(11 BYTE), 
	"CD_CID_OBITO" VARCHAR2(6 BYTE), 
	"NM_USUARIO_ALTA_MEDICA" VARCHAR2(30 BYTE), 
	"CD_PRESTADOR_EM_ATENDIMENTO" VARCHAR2(30 BYTE), 
	"CD_PRO_INT" VARCHAR2(10 BYTE), 
	"CD_PRO_INT_PROCEDIMENTO_ENTRAD" VARCHAR2(10 BYTE), 
	"CD_PROCEDIMENTO_ALTA" VARCHAR2(10 BYTE), 
	"CD_SSM_CIH" VARCHAR2(10 BYTE), 
	"CD_CONVENIO" NUMBER(3,0), 
	"CD_CID" VARCHAR2(6 BYTE), 
	"DS_PROGRAMA_ALTA" VARCHAR2(200 BYTE), 
	"DT_PROGRAMA_ALTA" DATE, 
	"NM_USUARIO_PROG_ALTA" VARCHAR2(30 BYTE), 
	"SN_OBITO" VARCHAR2(1 BYTE), 
	"SN_BUSCA_ATIVA" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"TP_BUSCA_ATIVA" VARCHAR2(1 BYTE) DEFAULT '0' NOT NULL ENABLE, 
	"DH_ALTA_MEDICA_LANCADA" DATE, 
	"CD_DOCUMENTO_CLINICO_DOC" NUMBER(8,0), 
	"CD_DOCUMENTO_CLINICO_MOT_ALT" NUMBER(8,0), 
	"CD_DOCUMENTO_CLINICO_ESTADIAM" NUMBER, 
	 CONSTRAINT "CNT_PW_REGISTRO_ALTA_PK" PRIMARY KEY ("CD_REGISTRO_ALTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MV2000_I"  ENABLE, 
	 CONSTRAINT "CNT_PW_REGISTRO_ALTA_1_CK" CHECK ( TP_SITUACAO IN ( 'FECHADA', 'CANCELADA' )) ENABLE, 
	 CONSTRAINT "CNT_PW_REGISTRO_ALTA_ATEND_FK" FOREIGN KEY ("CD_ATENDIMENTO")
	  REFERENCES "DBAMV"."ATENDIME" ("CD_ATENDIMENTO") ENABLE, 
	 CONSTRAINT "CNT_PW_REGISTRO_ALTA_PREST_FK" FOREIGN KEY ("CD_PRESTADOR")
	  REFERENCES "DBAMV"."PRESTADOR" ("CD_PRESTADOR") ENABLE, 
	 CONSTRAINT "CNT_PW_REG_ALTA_DOC_CLI_FK" FOREIGN KEY ("CD_DOCUMENTO_CLINICO")
	  REFERENCES "DBAMV"."PW_DOCUMENTO_CLINICO" ("CD_DOCUMENTO_CLINICO") ENABLE, 
	 CONSTRAINT "CNT_PW_REG_ALTA_DOC_CLI_EST_FK" FOREIGN KEY ("CD_DOCUMENTO_CLINICO_ESTADIAM")
	  REFERENCES "DBAMV"."PW_DOCUMENTO_CLINICO" ("CD_DOCUMENTO_CLINICO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MV2000_D" ;
 

   COMMENT ON COLUMN "DBAMV"."PW_REGISTRO_ALTA"."CD_REGISTRO_ALTA" IS 'Indica o código dos registros da tabela de registro de alta(pk).';
 
   COMMENT ON COLUMN "DBAMV"."PW_REGISTRO_ALTA"."DT_REGISTRO_ALTA" IS 'Indica a data da alta.';
 
   COMMENT ON COLUMN "DBAMV"."PW_REGISTRO_ALTA"."CD_ATENDIMENTO" IS 'Código do atendimento da alta.';
 
   COMMENT ON COLUMN "DBAMV"."PW_REGISTRO_ALTA"."CD_PRESTADOR" IS 'Código do prestador da alta.';
 
   COMMENT ON COLUMN "DBAMV"."PW_REGISTRO_ALTA"."CD_DOCUMENTO_CLINICO" IS 'Código do documento clínico (FK).';
 
   COMMENT ON COLUMN "DBAMV"."PW_REGISTRO_ALTA"."CD_USUARIO" IS 'Código do usuário da alta.';
 
   COMMENT ON COLUMN "DBAMV"."PW_REGISTRO_ALTA"."TP_SITUACAO" IS 'Tipo da situalão da alta, se ela esta Fechada ou Cancelada.';
 
   COMMENT ON COLUMN "DBAMV"."PW_REGISTRO_ALTA"."CD_DOCUMENTO_CLINICO_ESTADIAM" IS 'Indica o código do documento clínico do estadiamento criado junto com o finalização da alta';
 
   COMMENT ON TABLE "DBAMV"."PW_REGISTRO_ALTA"  IS 'Armazena as informações da alta do paciente.';
 

  CREATE INDEX "DBAMV"."CNT_PW_REG_ALTA_DOC_CLI_EST_IX" ON "DBAMV"."PW_REGISTRO_ALTA" ("CD_DOCUMENTO_CLINICO_ESTADIAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MV2000_I" ;
 

  CREATE INDEX "DBAMV"."IND_PW_REGISTRO_ALTA_ATEND_FK" ON "DBAMV"."PW_REGISTRO_ALTA" ("CD_ATENDIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MV2000_I" ;
 

  CREATE INDEX "DBAMV"."IND_PW_REGISTRO_ALTA_PREST_FK" ON "DBAMV"."PW_REGISTRO_ALTA" ("CD_PRESTADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MV2000_I" ;
 

  CREATE INDEX "DBAMV"."IND_PW_REG_ALTA_DOC_CLI_FK" ON "DBAMV"."PW_REGISTRO_ALTA" ("CD_DOCUMENTO_CLINICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MV2000_I" ;
 

  CREATE OR REPLACE TRIGGER "DBAMV"."TRG_SIC_CIH_ATENDIME" 

AFTER INSERT OR UPDATE OF cd_ssm_cih  ON dbamv.pw_registro_alta

FOR EACH ROW

BEGIN



    UPDATE dbamv.atendime SET cd_ssm_cih = :new.cd_ssm_cih  WHERE cd_atendimento = :new.cd_atendimento ;



END;
/
ALTER TRIGGER "DBAMV"."TRG_SIC_CIH_ATENDIME" ENABLE;
 
