SELECT DISTINCT
	 ORI.DS_ORI_ATE AS ORIGEM_ATENDIMENTO
	,COUNT(ATE.CD_ATENDIMENTO) AS TOTAL_POR_ORIGEM
FROM
    ATENDIME    ATE
    ,ORI_ATE     ORI
   -- PRESTADOR   PRE
WHERE
   -- ATE.CD_PRESTADOR = PRE.CD_PRESTADOR
    ATE.CD_ORI_ATE = ORI.CD_ORI_ATE
AND ATE.SN_RETORNO = 'N'
AND ATE.CD_ORI_ATE in(3,4,30,51)
and ATE.CD_CONVENIO not in(1,2)
and ATE.tp_atendimento in ('A','E')
and TO_CHAR(ATE.DT_ATENDIMENTO,'MM/YYYY')='01/2018'
GROUP BY 
    ORI.DS_ORI_ATE
    ,ORI.CD_SETOR
ORDER BY ORIGEM_ATENDIMENTO ASC;

