select NM_USUARIO from SYS.FUNCIONARIOS where DS_OBSERVACAO like 'T%I%' AND SN_ATIVO='S';
select * from SYS.FUNCIONARIOS; 
SELECT REPLACE((SUBSTR(CD_USUARIO,0,1) || SUBSTR(dbms_random.VALUE (1,3),1,6) ),',')from SYS.FUNCIONARIOS;--MATRICULA
SELECT REPLACE(SUBSTR(dbms_random.VALUE (1,3),1,6 ),',') from SYS.FUNCIONARIOS;--SENHA
set serveroutput on
SELECT RAWTOHEX(DBMS_OBFUSCATION_TOOLKIT.md5(input => utl_raw.cast_to_raw(REPLACE(SUBSTR(dbms_random.VALUE (1,3),1,6 ),',')))) from SYS.FUNCIONARIOS;--RAWTOHEX(DBMS_OBFUSCATION_TOOLKIT.md5(REPLACE(SUBSTR(dbms_random.VALUE (1,3),1,6 ),',')))
SELECT
    REPLACE((SUBSTR(CD_USUARIO,0,1) || SUBSTR(dbms_random.VALUE (1,3),1,6) ),',') AS CD_USUARIO,
    NM_USUARIO,
    RAWTOHEX(DBMS_OBFUSCATION_TOOLKIT.md5(input => utl_raw.cast_to_raw(REPLACE(SUBSTR(dbms_random.VALUE (1,3),1,6 ),',')))) AS CD_SENHA,
    (REPLACE(SUBSTR(dbms_random.VALUE (1,3),1,6 ),',')) AS TESTE_SENHA,
    DS_OBSERVACAO,
    (NULL)CD_PRESTADOR,
    CD_PAPEL,
    SN_ATIVO,
    TP_STATUS,
    CD_PROFISSAO,
    DT_NASCIMENTO,
    CD_IDIOMA
FROM
    SYS.FUNCIONARIOS
WHERE
SN_ATIVO='S' AND ROWNUM < 41
AND DS_OBSERVACAO IS NOT NULL